const flightsArr = [
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-sha,sha?date=',
    airline: 'PEK-SHA',
    airlineCN: '北京首都-上海虹桥',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1074,
    weekly: '>=70',
  },
  {
    url: ' https://flights.ctrip.com/itinerary/oneway/bjs,pek-sha,pvg?date=',
    airline: 'PEK-PVG',
    airlineCN: '北京首都-上海浦东',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1096,
    weekly: '>=70',
  },

  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-ctu,ctu?date=',
    airline: 'PEK-CTU',
    airlineCN: '北京首都-成都双流',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1557,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-can,can?date=',
    airline: 'PEK-CAN',
    airlineCN: '北京首都-广州白云',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1875,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-szx,szx?date=',
    airline: 'PEK-SZX',
    airlineCN: '北京首都-深圳宝安',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1887,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-ckg,ckg?date=',
    airline: 'PEK-CKG',
    airlineCN: '北京首都-重庆江北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1463,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-hgh,hgh?date=',
    airline: 'PEK-HGH',
    airlineCN: '北京首都-杭州萧山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1146,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-sia,xiy?date=',
    airline: 'PEK-XIY',
    airlineCN: '北京首都-西安咸阳',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 935,
    weekly: '>=70',
  },

  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-szx,szx?date=',
    airline: 'SHA-SZX',
    airlineCN: '上海虹桥-深圳宝安',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1207,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-ctu,ctu?date=',
    airline: 'SHA-CTU',
    airlineCN: '上海虹桥-成都双流',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1662,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-ckg,ckg?date=',
    airline: 'SHA-CKG',
    airlineCN: '上海虹桥-重庆江北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1420,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-tao,tao?date=',
    airline: 'SHA-TAO',
    airlineCN: '上海虹桥-青岛流亭',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 569,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-xiy,xiy?date=',
    airline: 'SHA-XIY',
    airlineCN: '上海虹桥-西安咸阳',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1231,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-xmn,xmn?date=',
    airline: 'SHA-XMN',
    airlineCN: '上海虹桥-厦门高崎',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 802,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-kmg,kmg?date=',
    airline: 'SHA-KMG',
    airlineCN: '上海虹桥-昆明长水',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1926,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-csx,csx?date=',
    airline: 'SHA-CSX',
    airlineCN: '上海虹桥-长沙黄花',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 853,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-she,she?date=',
    airline: 'SHA-SHE',
    airlineCN: '上海虹桥-沈阳桃仙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1175,
    weekly: '>=70',
  },

  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-szx,szx?date=',
    airline: 'PVG-SZX',
    airlineCN: '上海浦东-深圳宝安',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1231,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-ctu,ctu?date=',
    airline: 'PVG-CTU',
    airlineCN: '上海浦东-成都双流',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1706,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-ckg,ckg?date=',
    airline: 'PVG-CKG',
    airlineCN: '上海浦东-重庆江北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1463,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-tao,tao?date=',
    airline: 'PVG-TAO',
    airlineCN: '上海浦东-青岛流亭',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 583,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-xiy,xiy?date=',
    airline: 'PVG-XIY',
    airlineCN: '上海浦东-西安咸阳',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1274,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-xmn,xmn?date=',
    airline: 'PVG-XMN',
    airlineCN: '上海浦东-厦门高崎',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 816,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-kmg,kmg?date=',
    airline: 'PVG-KMG',
    airlineCN: '上海浦东-昆明长水',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1966,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-csx,csx?date=',
    airline: 'PVG-CSX',
    airlineCN: '上海浦东-长沙黄花',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 892,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-she,she?date=',
    airline: 'PVG-SHE',
    airlineCN: '上海浦东-沈阳桃仙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1175,
    weekly: '>=70',
  },

  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-sha,sha?date=',
    airline: 'CAN-SHA',
    airlineCN: '广州白云-上海虹桥',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1173,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-sha,pvg?date=',
    airline: 'CAN-PVG',
    airlineCN: '广州白云-上海浦东',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1201,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-ctu,ctu?date=',
    airline: 'CAN-CTU',
    airlineCN: '广州白云-成都双流',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1223,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-hgh,hgh?date=',
    airline: 'CAN-HGH',
    airlineCN: '广州白云-杭州萧山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1036,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-ckg,ckg?date=',
    airline: 'CAN-CKG',
    airlineCN: '广州白云-重庆江北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1036,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-nkg,nkg?date=',
    airline: 'CAN-NKG',
    airlineCN: '广州白云-南京禄口',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1075,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-hak,hak?date=',
    airline: 'CAN-HAK',
    airlineCN: '广州白云-海口美兰',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 483,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-xiy,xiy?date=',
    airline: 'CAN-XIY',
    airlineCN: '广州白云-西安咸阳',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1303,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/szx,szx-ckg,ckg?date=',
    airline: 'SZX-CKG',
    airlineCN: '深圳宝安-重庆江北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1062,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/szx,szx-hgh,hgh?date=',
    airline: 'SZX-HGH',
    airlineCN: '深圳宝安-杭州萧山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1069,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/szx,szx-ctu,ctu?date=',
    airline: 'SZX-CTU',
    airlineCN: '深圳宝安-成都双流',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1318,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/szx,szx-NKG,NKG?date=',
    airline: 'SZX-NKG',
    airlineCN: '深圳宝安-南京禄口',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1126,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/kmg,kmg-jhg,jhg?date=',
    airline: 'KMG-JHG',
    airlineCN: '昆明长水-西双版纳嘎洒',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 412,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/kmg,kmg-ctu,ctu?date=',
    airline: 'KMG-CTU',
    airlineCN: '昆明长水-成都双流',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 615,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-sha,sha?date=',
    airline: 'PKX-SHA',
    airlineCN: '北京大兴-上海虹桥',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1025,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-sha,pvg?date=',
    airline: 'PKX-PVG',
    airlineCN: '北京大兴-上海浦东',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1049,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-ctu,ctu?date=',
    airline: 'PKX-CTU',
    airlineCN: '北京大兴-成都双流',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1505,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-can,can?date=',
    airline: 'PKX-CAN',
    airlineCN: '北京大兴-广州白云',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1811,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-szx,szx?date=',
    airline: 'PKX-SZX',
    airlineCN: '北京大兴-深圳宝安',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1951,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-ckg?date=',
    airline: 'PKX-CKG',
    airlineCN: '北京大兴-重庆江北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1406,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-hgh,hgh?date=',
    airline: 'PKX-HGH',
    airlineCN: '北京大兴-杭州萧山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1093,
    weekly: '>=70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-sia,xiy?date=',
    airline: 'PKX-XIY',
    airlineCN: '北京大兴-西安咸阳',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 883,
    weekly: '>=70',
  },

  // ----
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-foc,foc?date=',
    airline: 'PEK-FOC',
    airlineCN: '北京首都-福州长乐',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1594,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-zuh,zuh?date=',
    airline: 'PEK-ZUH',
    airlineCN: '北京首都-珠海金湾',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 2026,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-she,she?date=',
    airline: 'PEK-SHE',
    airlineCN: '北京首都-沈阳桃仙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 606,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-wnz,wnz?date=',
    airline: 'PEK-WNZ',
    airlineCN: '北京首都-温州龙湾',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1405,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-ynt,ynt?date=',
    airline: 'PEK-YNT',
    airlineCN: '北京首都-烟台蓬莱',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 465,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-swa,swa?date=',
    airline: 'SHA-SWA',
    airlineCN: '上海虹桥-揭阳潮汕',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 972,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-nng,nng?date=',
    airline: 'SHA-NNG',
    airlineCN: '上海虹桥-南宁吴圩',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1615,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-xnn,xnn?date=',
    airline: 'SHA-XNN',
    airlineCN: '上海虹桥-西宁曹家堡',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1877,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,sha-JJN,JJN?date=',
    airline: 'SHA-JJN',
    airlineCN: '上海虹桥-泉州晋江',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 759,
    weekly: '35-70',
  },

  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-swa,swa?date=',
    airline: 'PVG-SWA',
    airlineCN: '上海浦东-揭阳潮汕',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 990,
    weekly: '35-70',
  },

  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-nng,nng?date=',
    airline: 'PVG-NNG',
    airlineCN: '上海浦东-南宁吴圩',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1649,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-xnn,xnn?date=',
    airline: 'PVG-XNN',
    airlineCN: '上海浦东-西宁曹家堡',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1919,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-JJN,JJN?date=',
    airline: 'PVG-JJN',
    airlineCN: '上海浦东-泉州晋江',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 771,
    weekly: '35-70',
  },

  {
    url: 'https://flights.ctrip.com/itinerary/oneway/can,can-lhw,lhw?date=',
    airline: 'CAN-LHW',
    airlineCN: '广州白云-兰州中川',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1727,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/szx,szx-wux,wux?date=',
    airline: 'SZX-WUX',
    airlineCN: '深圳宝安-无锡苏南硕放',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1180,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KMG,KMG-XMN,XMN?date=',
    airline: 'KMG-XMN',
    airlineCN: '昆明长水-厦门高崎',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1536,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KMG,KMG-SYM,SYM?date=',
    airline: 'KMG-SYM',
    airlineCN: '昆明长水-普洱思茅',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 326,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-TNA,TNA?date=',
    airline: 'CTU-TNA',
    airlineCN: '成都双流-济南遥墙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1411,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-CSX,CSX?date=',
    airline: 'CTU-CSX',
    airlineCN: '成都双流-长沙黄花',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 938,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-TSN,TSN?date=',
    airline: 'CKG-TSN',
    airlineCN: '重庆江北-天津滨海',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1432,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-LJG,LJG?date=',
    airline: 'CKG-LJG',
    airlineCN: '重庆江北-丽江三义',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 712,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-SYX,SYX?date=',
    airline: 'CKG-SYX',
    airlineCN: '重庆江北-三亚凤凰',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1296,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-WUH,WUH?date=',
    airline: 'CKG-WUH',
    airlineCN: '重庆江北-武汉天河',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 738,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-HAK,HAK?date=',
    airline: 'CKG-HAK',
    airlineCN: '重庆江北-海口美兰',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1151,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-WNZ,WNZ?date=',
    airline: 'CKG-WNZ',
    airlineCN: '重庆江北-温州龙湾',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1401,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/XIY,XIY-TSN,TSN?date=',
    airline: 'XIY-TSN',
    airlineCN: '西安咸阳-天津滨海',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 926,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/XIY,XIY-KHN,KHN?date=',
    airline: 'XIY-KHN',
    airlineCN: '西安咸阳-南昌昌北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 918,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CSX,CSX-TSN,TSN?date=',
    airline: 'CSX-TSN',
    airlineCN: '长沙黄花-天津滨海',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1271,
    weekly: '35-70',
  },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/dlc,dlc-jxa,jxa?date=',
  //   airline: 'DLC-JXA',
  //   airlineCN: '大连周水子-鸡西兴凯湖',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 1166,
  //   weekly: '666888',
  // },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CSX,CSX-KMG,KMG?date=',
    airline: 'CSX-KMG',
    airlineCN: '长沙黄花-昆明长水',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1078,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HGH,HGH-TYN,TYN?date=',
    airline: 'HGH-TYN',
    airlineCN: '杭州萧山-太原武宿',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1102,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HGH,HGH-SYX,SYX?date=',
    airline: 'HGH-SYX',
    airlineCN: '杭州萧山-三亚凤凰',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1729,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HRB,HRB-NKG,NKG?date=',
    airline: 'HRB-NKG',
    airlineCN: '哈尔滨太平-南京禄口',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1668,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HRB,HRB-TNA,TNA?date=',
    airline: 'HRB-TNA',
    airlineCN: '哈尔滨太平-济南遥墙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1232,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-FOC,FOC?date=',
    airline: 'PKX-FOC',
    airlineCN: '北京大兴-福州长乐',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1536,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-ZUH,ZUH?date=',
    airline: 'PKX-ZUH',
    airlineCN: '北京大兴-珠海金湾',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1962,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-SHE,SHE?date=',
    airline: 'PKX-SHE',
    airlineCN: '北京大兴-沈阳桃仙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 644,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-WNZ,WNZ?date=',
    airline: 'PKX-WNZ',
    airlineCN: '北京大兴-温州龙湾',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1350,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-YNT,YNT?date=',
    airline: 'PKX-YNT',
    airlineCN: '北京大兴-烟台蓬莱',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 448,
    weekly: '35-70',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PEK,PEK-WEH,WEH?date=',
    airline: 'PEK-WEH',
    airlineCN: '北京首都-威海大水泊',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 586,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/SHA,SHA-URC,URC?date=',
    airline: 'SHA-URC',
    airlineCN: '上海虹桥-乌鲁木齐地窝堡',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 3277,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/SHA,pvg-URC,URC?date=',
    airline: 'PVG-URC',
    airlineCN: '上海浦东-乌鲁木齐地窝堡',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 3316,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CAN,CAN-CSX,CSX?date=',
    airline: 'CAN-CSX',
    airlineCN: '广州白云-长沙黄花',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 531,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/SZX,SZX-TYN,TYN?date=',
    airline: 'SZX-TYN',
    airlineCN: '广州白云-太原武宿',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1679,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KMG,KMG-WUX,WUX?date=',
    airline: 'KMG-WUX',
    airlineCN: '昆明长水-无锡苏南硕放',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1853,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KMG,KMG-JJN,JJN?date=',
    airline: 'KMG-JJN',
    airlineCN: '昆明长水-泉州晋江',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1580,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KMG,KMG-SWA,SWA?date=',
    airline: 'KMG-SWA',
    airlineCN: '昆明长水-揭阳潮汕',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1386,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-DLU,DLU?date=',
    airline: 'CTU-DLU',
    airlineCN: '成都双流-大理',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 652,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-TYN,TYN?date=',
    airline: 'CTU-TYN',
    airlineCN: '成都双流-太原武宿',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1127,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-WNZ,WNZ?date=',
    airline: 'CTU-WNZ',
    airlineCN: '成都双流-温州龙湾',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1668,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-XIC,XIC?date=',
    airline: 'CTU-XIC',
    airlineCN: '成都双流-西昌青山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 334,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-ZUH,ZUH?date=',
    airline: 'CTU-ZUH',
    airlineCN: '成都双流-珠海金湾',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1336,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-JHG,JHG?date=',
    airline: 'CKG-JHG',
    airlineCN: '重庆江北-西双版纳嘎洒',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1040,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-JJN,JJN?date=',
    airline: 'CKG-JJN',
    airlineCN: '重庆江北-泉州晋江',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1302,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/XIY,XIY-LJG,LJG?date=',
    airline: 'XIY-LJG',
    airlineCN: '西安咸阳-丽江三义',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1185,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/XIY,XIY-NNG,NNG?date=',
    airline: 'XIY-NNG',
    airlineCN: '西安咸阳-南宁吴圩',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1313,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/XIY,XIY-DSN,DSN?date=',
    airline: 'XIY-DSN',
    airlineCN: '西安咸阳-鄂尔多斯伊金霍洛',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 569,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CSX,CSX-XNN,XNN?date=',
    airline: 'CSX-XNN',
    airlineCN: '长沙黄花-西宁曹家堡',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1399,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CSX,CSX-SWA,SWA?date=',
    airline: 'CSX-SWA',
    airlineCN: '长沙黄花-揭阳潮汕',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 610,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HGH,HGH-CGQ,CGQ?date=',
    airline: 'HGH-CGQ',
    airlineCN: '杭州萧山-长春龙嘉',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1597,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HRB,HRB-TSN,TSN?date=',
    airline: 'HRB-TSN',
    airlineCN: '哈尔滨太平-天津滨海',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1028,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HAK,HAK-NKG,NKG?date=',
    airline: 'HAK-NKG',
    airlineCN: '海口美兰-南京禄口',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1555,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HAK,HAK-SWA,SWA?date=',
    airline: 'HAK-SWA',
    airlineCN: '海口美兰-揭阳潮汕',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 742,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/NNG,NNG-FOC,FOC?date=',
    airline: 'NNG-FOC',
    airlineCN: '南宁吴圩-福州长乐',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1223,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/NNG,NNG-XMN,XMN?date=',
    airline: 'NNG-XMN',
    airlineCN: '南宁吴圩-厦门高崎',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1038,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/ZUH,ZUH-NKG,NKG?date=',
    airline: 'ZUH-NKG',
    airlineCN: '珠海金湾-南京禄口',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1208,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/ZUH,ZUH-WUH,WUH?date=',
    airline: 'ZUH-WUH',
    airlineCN: '珠海金湾-武汉天河',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 975,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/LJG,LJG-CGO,CGO?date=',
    airline: 'LJG-CGO',
    airlineCN: '丽江三义-郑州新郑',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1564,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/LJG,LJG-JHG,JHG?date=',
    airline: 'LJG-JHG',
    airlineCN: '丽江三义-西双版纳嘎洒',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 524,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-WEH,WEH?date=',
    airline: 'PKX-WEH',
    airlineCN: '北京大兴-威海大水泊',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 570,
    weekly: '7-35',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PEK,PEK-LCX,LCX?date=',
    airline: 'PEK-LCX',
    airlineCN: '北京首都-龙岩冠豸山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1597,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PEK,PEK-RIZ,RIZ?date=',
    airline: 'PEK-RIZ',
    airlineCN: '北京首都-日照山字河',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 571,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/SHA,SHA-YKH,YKH?date=',
    airline: 'SHA-YKH',
    airlineCN: '上海虹桥-营口兰旗',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1041,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/SHA,PVG-YKH,YKH?date=',
    airline: 'PVG-YKH',
    airlineCN: '上海浦东-营口兰旗',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1044,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CAN,CAN-YNZ,YNZ?date=',
    airline: 'CAN-YNZ',
    airlineCN: '广州白云-盐城南洋',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1300,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/SZX,SZX-RIZ,RIZ?date=',
    airline: 'SZX-RIZ',
    airlineCN: '深圳宝安-日照山字河',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1512,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-KHG,KHG?date=',
    airline: 'CTU-KHG',
    airlineCN: '成都双流-喀什',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 2721,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CTU,CTU-LYG,LYG?date=',
    airline: 'CTU-LYG',
    airlineCN: '成都双流-连云港白塔埠',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1468,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-THQ,THQ?date=',
    airline: 'CKG-THQ',
    airlineCN: '重庆江北-天水麦积山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 542,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-BAV,BAV?date=',
    airline: 'CKG-BAV',
    airlineCN: '重庆江北-包头东河',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1241,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CKG,CKG-BFJ,BFJ?date=',
    airline: 'CKG-BFJ',
    airlineCN: '重庆江北-毕节飞雄',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 298,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/XIY,XIY-WEH,WEH?date=',
    airline: 'XIY-WEH',
    airlineCN: '西安咸阳-威海大水泊',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1254,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HRB,HRB-WUT,WUT?date=',
    airline: 'HRB-WUT',
    airlineCN: '哈尔滨太平-忻州五台山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1345,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/HAK,HAK-MIG,MIG?date=',
    airline: 'HAK-MIG',
    airlineCN: '海南美兰-绵阳南郊',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1396,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/NNG,NNG-XUZ,XUZ?date=',
    airline: 'NNG-XUZ',
    airlineCN: '南宁吴圩-徐州观音',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1565,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/NNG,NNG-YCU,YCU?date=',
    airline: 'NNG-YCU',
    airlineCN: '南宁吴圩-运城张孝',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1402,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/NNG,NNG-CZX,CZX?date=',
    airline: 'NNG-CZX',
    airlineCN: '南宁吴圩-常州奔牛',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1542,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/ZUH,ZUH-LYG,LYG?date=',
    airline: 'ZUH-LYG',
    airlineCN: '珠海金湾-连云港白塔埠',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1493,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/ZUH,ZUH-INC,INC?date=',
    airline: 'ZUH-INC',
    airlineCN: '珠海金湾-银川河东',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1928,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/DLC,DLC-HDG,HDG?date=',
    airline: 'DLC-HDG',
    airlineCN: '大连周水子-邯郸',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 683,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/DLC,DLC-JSJ,JSJ?date=',
    airline: 'DLC-JSJ',
    airlineCN: '大连周水子-建三江',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1278,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/DLC,DLC-YNJ,YNJ?date=',
    airline: 'DLC-YNJ',
    airlineCN: '大连周水子-延吉朝阳川',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 795,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/DLC,DLC-CIF,CIF?date=',
    airline: 'DLC-CIF',
    airlineCN: '大连周水子-赤峰玉龙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 426,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KWE,KWE-BHY,BHY?date=',
    airline: 'KWE-BHY',
    airlineCN: '贵阳龙洞堡-北海福成',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 609,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KWE,KWE-LZO,LZO?date=',
    airline: 'KWE-LZO',
    airlineCN: '贵阳龙洞堡-泸州云龙',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 292,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/KWE,KWE-XIC,XIC?date=',
    airline: 'KWE-XIC',
    airlineCN: '贵阳龙洞堡-西昌青山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 485,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/AHJ,AHJ-LXA,LXA?date=',
    airline: 'AHJ-LXA',
    airlineCN: '红原阿坝红原-拉萨贡嘎',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1150,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CZX,CZX-JJN,JJN?date=',
    airline: 'CZX-JJN',
    airlineCN: '常州奔牛-泉州晋江',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 798,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/CGQ,CGQ-YNJ,YNJ?date=',
    airline: 'CGQ-YNJ',
    airlineCN: '长春龙嘉-延吉朝阳川',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 329,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/DLU,DLU-KHN,KHN?date=',
    airline: 'DLU-KHN',
    airlineCN: '大理-南昌昌北',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1582,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-LCX,LCX?date=',
    airline: 'PKX-LCX',
    airlineCN: '北京大兴-龙岩冠豸山',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 1534,
    weekly: '<7',
  },
  {
    url: 'https://flights.ctrip.com/itinerary/oneway/PKX,PKX-RIZ,RIZ?date=',
    airline: 'PKX-RIZ',
    airlineCN: '北京大兴-日照山字河',
    zone: 'Domestic',
    zoneCode: 1,
    distance: 523,
    weekly: '<7',
  },
  // ------

  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/sha-can?date=',
  //   airline: 'SHA-CAN',
  //   airlineCN: '上海虹桥-广州白云',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 1173,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pek-kmg,kmg?date=',
  //   airline: 'PEK-KMG',
  //   airlineCN: '北京首都-昆明长水',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 2092,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/bjs,pkx-kmg,kmg?date=',
  //   airline: 'PKX-KMG',
  //   airlineCN: '北京大兴-昆明长水',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 2035,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/ctu,ctu-szx,szx?date=',
  //   airline: 'CTU-SZX',
  //   airlineCN: '成都双流-深圳宝安',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 1318,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/ctu,ctu-can,can?date=',
  //   airline: 'CTU-CAN',
  //   airlineCN: '成都双流-广州白云',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 1223,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/ckg,ckg-szx,szx?date=',
  //   airline: 'CKG-SZX',
  //   airlineCN: '重庆江北-深圳宝安',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 1062,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/szx,szx-hgh,hgh?date=',
  //   airline: 'SZX-HGH',
  //   airlineCN: '深圳宝安-杭州萧山',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 1069,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/ckg,ckg-can?date=',
  //   airline: 'CKG-CAN',
  //   airlineCN: '重庆江北-广州白云',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 965,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/can-kmg,kmg?date=',
  //   airline: 'CAN-KMG',
  //   airlineCN: '广州白云-昆明长水',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 1069,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/sha,pvg-dlc,dlc?date=',
  //   airline: 'SHA-DLC',
  //   airlineCN: '上海浦东-大连周水子',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 868,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/ctu,ctu-kmg,kmg?date=',
  //   airline: 'CTU-KMG',
  //   airlineCN: '成都双流-昆明长水',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 615,
  // },
  // {
  //   url: 'https://flights.ctrip.com/itinerary/oneway/kmg,kmg-jhg,jhg?date=',
  //   airline: 'KMG-JHG',
  //   airlineCN: '昆明长水-西双版纳嘎洒',
  //   zone: 'Domestic',
  //   zoneCode: 1,
  //   distance: 412,
  // },
];

module.exports = flightsArr;
